#pragma once

#include "pLoginRequest.h"
#include "pLoginResponse.h"
#include "pRole.h"
#include "pGSConnect.h"
#include "pPlayerInfo.h"
#include "pItem.h"
#include "pItemAction.h"
#include "pMapInfo.h"
#include "pPetInfo.h"
#include "pPetAction.h"
#include "pPetMagic.h"
#include "pPetShop.h"
#include "pTick.h"
#include "pWalk.h"
#include "pAction.h"
#include "pDirection.h"
#include "pColor.h"
#include "pColosseum.h"
#include "pMessage.h"
#include "pFriend.h"
#include "pUserInfo.h"
#include "pAction.h"
#include "pRename.h"
#include "pUserAttribute.h"
#include "pUserLevelUp.h"
#include "pPetLevelUp.h"

#include "pTeam.h"
#include "pTeamMember.h"

#include "pNpcInfo.h"
#include "pNpc.h"
#include "pNpcDialogue.h"
#include "pNpcAction.h"

#include "pBattleState.h"
#include "pEnemyInfo.h"
#include "pFighterInfo.h"
#include "pBattleAction.h"
#include "pNormalAct.h"
#include "pItemAct.h"
#include "pBattleRound.h"
#include "pBattleResult.h"