#pragma once

extern Uint32 FIRSTCUSTOMEVENT;
extern Uint32 CUSTOMEVENT_WINDOW;
enum {
	WINDOW_CLOSE,
	WINDOW_CLOSE_OK,
	WINDOW_CLOSE_BACK,
	WINDOW_CLOSE_PROMPT_OK,
	WINDOW_CLOSE_PROMPT_ERROR
};

extern Uint32 CUSTOMEVENT_WIDGET;
enum {
	WIDGET_FOCUS_GAINED,
	WIDGET_FOCUS_LOST
};


extern Uint32 CUSTOMEVENT_PLAYER;
enum {
	PLAYER_RENAME,
};