#pragma once

enum GAMEMODE {
	GAMEMODE_NONE = 0,
	GAMEMODE_SELECTTEAM,
	GAMEMODE_JOINTEAM,
};

enum ChatChannel {
	ccNone = 0,
	nnUnknown = 2000,
	ccPrivate = 2001,
	ccAction = 2002,
	ccTeam = 2003,
	ccGuild = 2004,
	ccSystem = 2005,
	ccSpouse = 2006,
	ccNormal = 2007,
	ccShout = 2008,
	ccFriend = 2009,
	ccBroadcast = 2010,
	ccGM = 2011,
	ccHidden = 2101,
	ccVendor = 2104,
	cWebsite = 2105
};

enum HorizontalAlignment {
	HORIZONTAL_LEFT,
	HORIZONTAL_CENTER,
	HORIZONTAL_RIGHT
};

enum VerticalAlignment {
	VERTICAL_TOP,
	VERTICAL_CENTER,
	VERTICAL_BOTTOM
};

enum Anchor {
	ANCOR_TOPLEFT,
	ANCOR_CENTERLEFT,
	ANCOR_BOTTOMLEFT,
	ANCOR_TOPMIDDLE,
	ANCOR_CENTER,
	ANCOR_BOTTOMMIDDLE,
	ANCOR_TOPRIGHT,
	ANCOR_CENTERRIGHT,
	ANCOR_BOTTOMRIGHT
};

enum EffectType {
	EFFECT_NONE,
	EFFECT_FLASHDOWN,
	EFFECT_READY,
	EFFECT_FAINT,
	EFFECT_HEAL,
	EFFECT_POISON,
	EFFECT_MIRROR,
	EFFECT_SPHERE,
	EFFECT_THINK,
};

enum EMOTE {
	EMOTE_STANDBY = 0,
	EMOTE_WALK,
	EMOTE_ATTACK1,
	EMOTE_WOUND,
	EMOTE_FAINT,
	EMOTE_LIE,
	EMOTE_WAVE,
	EMOTE_KNEEL,
	EMOTE_SAD,
	EMOTE_ANGRY,
	EMOTE_SIT,
	EMOTE_DEFEND,
	EMOTE_LAUGH,
	EMOTE_BOW,
	EMOTE_ATTACKSPECIAL,
	EMOTE_CAST,
	EMOTE_FILL,
	EMOTE_ATTACK2,
	EMOTE_ATTACK3,
};

//Battle Info
const DWORD	_IDMSK_PET		= 0x80000000;
const DWORD _IDMSK_MONSTER	= 0xC0000000;

enum { OBJ_NONE = 1234, OBJ_MONSTER, OBJ_PET, OBJ_USER, OBJ_ITEM };

enum { OBJTYPE_MONSTER = 0, OBJTYPE_VSPET, OBJTYPE_VSPLAYER, OBJTYPE_FRIENDPET, OBJTYPE_FRIENDPLAYER };

class Texture;
using Asset = std::shared_ptr<Texture>;